from typing import Protocol

from domain.entities.user import User


class UserRepository(Protocol):
    async def get_by_social_id(self, social_id: int) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
